//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diet_note {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class xml : global::System.Configuration.ApplicationSettingsBase {
        
        private static xml defaultInstance = ((xml)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new xml())));
        
        public static xml Default {
            get {
                return defaultInstance;
            }
        }
    }
}
